### ISSUE TITLE
Thinstation 6.1 reconnection behavior

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#423] opened 2019-06-05 06:47 UTC
Hello!
I use Thinstation 6.1 for Horizon View virtual desktops. After update to Thinstation 6.1 i see change in the reconnection procedure.

Default behavior: after vmview session end I see  string "Click yes to reconnect". If I click YES then I reconnect, else if i click NO then I see splash screen.
I try different options:

RECONNECT_PROMPT=OFF:  I see splash screen only.
RECONNECT_PROMPT=MENU01: I see the menu. if I click "Shutdown" reconnect happens. After 1 min nothing happens.

I assume that shutdown cannot be called for some reason.

I want to return the old behavior: after click NO system shutdown immediately. How can I do this?

**Comment by Doncuppjr** [comment] 2019-06-05 14:44
Hmmm, I’ll look into this.


Sent from Yahoo Mail for iPhone


On Tuesday, June 4, 2019, 11:47 PM, mcsn747 <notifications@github.com> wrote:


Hello!
I use Thinstation 6.1 for Horizon View virtual desktops. After update to Thinstation 6.1 i see change in the reconnection procedure.

Default behavior: after vmview session end I see string "Click yes to reconnect". If I click YES then I reconnect, else if i click NO then I see splash screen.
I try different options:

RECONNECT_PROMPT=OFF: I see splash screen only.
RECONNECT_PROMPT=MENU01: I see the menu. if I click "Shutdown" reconnect happens. After 1 min nothing happens.

I assume that shutdown cannot be called for some reason.

I want to return the old behavior: after click NO system shutdown immediately. How can I do this?

**Comment by Thinstation** [comment] 2019-06-08 20:38
Should be fixed now. Thank you for reporting.

**Closed as completed by Thinstation** 2019-06-08 20:38 UTC

**Comment by mcsn747** [comment] 2019-06-10 09:26
Hello!

Do you already commited fix? I fetched the repository today and builded a new image. 
If i don't set RECONNECT_PROMPT, then i see menu "Click yes to reconnect". If i click NO, then i see splash screen after exitng the application. No shutdown or reboot happens.
If i set RECONNECT_PROMPT=MENU01, then clicking on "Shutdown" still causes reconnection to vmware client.

I builded my previous image in March, and it had a different behavior.  After exiting Windows I didn't shutdown the computer straight clicking NO on menu "Click yes to reconnect". Can you get it back?

**Comment by Doncuppjr** [comment] 2019-06-10 13:14
Hmmmm, indefinently commites the change, and it works.


Sent from Yahoo Mail for iPhone


On Monday, June 10, 2019, 2:26 AM, mcsn747 <notifications@github.com> wrote:


Hello!

Do you already commited fix? I fetched the repository today and builded a new image.
If i don't set RECONNECT_PROMPT, then i see splash screen after exitng the application. No shutdown or reboot happens.
If i set RECONNECT_PROMPT=MENU01, then clicking on "Shutdown" still causes reconnection to vmware client.

I builded my previous image in March, and it had a different behavior. I could shutdown the computer clicking NO on menu "Click yes to reconnect". Can you get it back?

**Comment by Doncuppjr** [comment] 2019-06-10 13:16
Try update systemd Before your next build.


Sent from Yahoo Mail for iPhone


On Monday, June 10, 2019, 2:26 AM, mcsn747 <notifications@github.com> wrote:


Hello!

Do you already commited fix? I fetched the repository today and builded a new image.
If i don't set RECONNECT_PROMPT, then i see splash screen after exitng the application. No shutdown or reboot happens.
If i set RECONNECT_PROMPT=MENU01, then clicking on "Shutdown" still causes reconnection to vmware client.

I builded my previous image in March, and it had a different behavior. I could shutdown the computer clicking NO on menu "Click yes to reconnect". Can you get it back?

**Comment by mcsn747** [comment] 2019-06-11 09:40
I updated systemd to 329-2, then rebuild image.

I see that the script dialog.functions creates a file /tmp/shutdown, the contents of which are written to the crontab for tsuser.
In my case for example:
```
crontab -l
47  * * * * shutdown
54  * * * * shutdown
```
This entries is not working! To shutdown or restart, the user must be root or use sudo. 
I login as tsuser and try to reboot:
```
reboot
Failed to set wall message, ignoring: The name org.freedesktop.PolicyKit1 was not provided by any .service files
Failed to reboot system via logind: The name org.freedesktop.PolicyKit1 was not provided by any .service files
Failed to talk to init daemon.
```

Next i update polkit. Nothing changes. 
How can this work for you?

**Comment by mcsn747** [comment] 2019-06-11 10:19
I can do the following

as root:
`chmod u+s /bin/poweroff`

then as tsuser
`/bin/poweroff`

Next trouble: this command closes all sessions, but  doesn't turn off the power. May be ACPI service is not working correctly.

**Comment by Doncuppjr** [comment] 2019-06-11 13:38
The problem was that systemd provided its own link called shutdown, that replaced the special ThinStation script for shutting down. The fix was to change the repackage script for systemd to drop it’s shutdown, so ours is called. 
Maybe your checkout is in a bad state. Nuke and pave?


Sent from Yahoo Mail for iPhone


On Tuesday, June 11, 2019, 2:40 AM, mcsn747 <notifications@github.com> wrote:


I updated systemd to 329-2, then rebuild image.

I see that the script dialog.functions creates a file /tmp/shutdown, the contents of which are written to the crontab for tsuser.
In my case for example:
crontab -l
47  * * * * shutdown
54  * * * * shutdown

This entries is not working! To shutdown or restart, the user must be root or use sudo.
I login as tsuser and try to reboot:
reboot
Failed to set wall message, ignoring: The name org.freedesktop.PolicyKit1 was not provided by any .service files
Failed to reboot system via logind: The name org.freedesktop.PolicyKit1 was not provided by any .service files
Failed to talk to init daemon.

Next i update polkit. Nothing changes.
How can this work for you?

**Comment by Doncuppjr** [comment] 2019-06-11 13:39
That would explain why shutdown doesn’t work, as the last thing called by shutdown script is poweroff.
All modules build?


Sent from Yahoo Mail for iPhone


On Tuesday, June 11, 2019, 3:19 AM, mcsn747 <notifications@github.com> wrote:


I can do the following

as root:
chmod u+s /bin/poweroff

then as tsuser
/bin/poweroff

Next trouble: this command closes all sessions, but doesn't turn off the power. May be ACPI service is not working correctly.

**Comment by mcsn747** [comment] 2019-06-13 10:25
I cloned a сurrent 6.1-stable build again today and build it with --allmodules. No shutdown is  possible. 
I don't think the build is corrupted.
According this https://wiki.archlinux.org/index.php/Allow_users_to_shutdown, i guess the easiest solution is to use sudo for shutdown.

**Comment by mcsn747** [comment] 2019-06-13 10:29
I can check it, just don't remember what package sudo is in.

**Comment by Thinstation** [comment] 2019-06-13 13:44
Which window manager are you using?

**Comment by mcsn747** [comment] 2019-06-14 06:17
I'm using icewm:

SESSION_0_TYPE=icewm
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=on

**Comment by Thinstation** [comment] 2019-06-18 21:59
O.k.
I think I have this fixed now.
You will also need to include package polkit in build.conf, if you are using a non-root user

**Comment by mcsn747** [comment] 2019-06-19 03:55
Yes, I can confirm: currently "Click to reconnect" -> NO or shutdown command closes all sessions and blacks screen. But the computer does not turn off. I already wrote about this in a previous comment.
Perhaps there is a package that will help?

**Comment by Doncuppjr** [comment] 2019-06-19 12:45
Allmodules 


Sent from Yahoo Mail for iPhone


On Tuesday, June 18, 2019, 8:55 PM, mcsn747 <notifications@github.com> wrote:


Yes, I can confirm: currently "Click to reconnect" -> NO or shutdown command closes all sessions and blacks screen. But the computer does not turn off. I already wrote about this in a previous comment.
Perhaps there is a package that will help?

**Comment by mcsn747** [comment] 2019-06-20 04:18
I built with allmodules, the same behavior. I want to full poweroff, not halt with power on.

**Comment by mcsn747** [comment] 2019-06-20 05:42
My motherboard has ACPI 2.0 and ACPI APIC support, and I have boot kernel option acpi=on enabled. Shutdown worked well in Thinstation 5.5. Now I tried to set acpi=off, acpi=noirq, noapic, nolapic, pnpacpi=off options - no success.  pci=noacpi break boot.

**Comment by mcsn747** [comment] 2019-06-26 03:17
Hello! Do you have any news or solutions?

**Comment by Thinstation** [comment] 2019-06-26 03:58
> You will also need to include package polkit in build.conf, if you are using a non-root user

There is an example

cp /build/conf/openbox/* /build/.

echo "
package polkit
package freerdp
param tsuser tsuser
param tsuserpassword pleasechangeme
" >> /build/build.conf

echo "
RECONNECT_PROMPT=MENU01
SESSION_1_TYPE=freerdp
SESSION_1_AUTOSTART=on
">> /build/thinstation.conf.buildtime

stb

bt cd

Now connect to a server, disconnect, select shutdown

**Comment by mcsn747** [comment] 2019-06-26 11:26
Today I cloned repo and built the image with your settings. Full shutdown is not possible: the monitor is black, but powered, keyboard and mouse off, and the computer remains on. The computer is in halt state.

**Comment by Thinstation** [comment] 2019-06-26 17:31
Add xterm package, and as the unprivileged user call /bin/shutdown

**Comment by mcsn747** [comment] 2019-06-27 04:23
I did it, and nothing has changed. 
Secondly I logged via ssh as root - even he cannot shutdown the computer.

**Comment by Thinstation** [comment] 2019-06-27 16:35
What's the deal with your hardware? BIOS reset to default?

**Comment by mcsn747** [comment] 2019-06-28 04:35
Hmm, you were right: I reset BIOS to defaults, and computer began to shutdown.
ACPI 2.0 support must be OFF - in my case.
Thank you!
