### ISSUE TITLE
Issues while switching to 6.1.1

### ISSUE THREAD

**Issue by Seg22** [Thinstation/thinstation#347] opened 2018-11-29 14:00 UTC
Hey guys, it´s me again.

While switching to 6.1.1 i got some Problems with my config files.

First of all, i´m doing a micro linux just to start rdesktop, so i´m only including my machine, rdesktop, autonet etc. i´m at 56mb right now.

First issue: 
my Keyboard layout seems to be en_US even though i only include locale-de_DE
i´ve already tried the LOCALE=de_DE and KEYBOARD_MAP=de but that doesn´t work
i can see that my thinstation.conf.network is loaded while pxe booting
In my build.log i can see that de_DE is loading as wanted

Second issue:
rdesktop is starting but with no options
right now i´m using
SESSION_0_TITLE="ITCRemote"
SESSION_0_TYPE=rdesktop
SESSION_0_RDESKTOP_SERVER=192.168.110.2
SESSION_0_RDESKTOP_OPTIONS="-d ITCTEST -u '' -p '' -x l -P -z -f -k de -r disk:E=/mnt/usbdevice -r sound:local"
SESSION_0_AUTOSTART=On

that worked with 5.5 but now it just opens the rdesktop window with nothing filled.

Hope you have any idea how that can work.

**Comment by Thinstation** [comment] 2018-11-30 00:03
I can confirm the second issue, and I have pushed a commit to fix. I’ll look into the locale issue.

**Comment by Seg22** [comment] 2018-11-30 12:08
Oh and since 6.1 the start splash doesn´t work.
While booting it says "a start job is running for start splash" for 1:30 min.
After that time it aborts the splash and starts the linux regular but tells me to look in a log file, i just didn´t had the time to look into it but i will do it on Monday.

**Comment by Thinstation** [comment] 2018-12-04 22:20
Can you please confirm if any of these bugs are still an issue in 6.1?

**Comment by Seg22** [comment] 2018-12-05 08:19
Hey Thin,

first of all, my last Ticket "Install 6.1 on VM - not able to go graphical" isn´t done yet. I´ve tried to install the new 1201 iso in xen and now i only got a blackscreen, not even a command line.

Second:
I´ve updated Devstation via Start/DevStation/Update Devstation and build a new image.

Splash: still doesn´t work (i know you´ve excluded this, i hope just for now)

Keyboard: if i start xfwm4 first the keyboard is de_DE (in terminal and also in rdesktop if i start it then)
If i autostart directly into rdesktop the keyboard is en_US or sth. maybe this issue get´s together with the rdesktop issue

rdesktop: I´ve checkt my options through terminal and found out that -x l doesn´t work for us
so i´m now using:

SESSION_0_TITLE="ITCRemote"
SESSION_0_TYPE=rdesktop
SESSION_0_RDESKTOP_SERVER=192.168.110.2
SESSION_0_RDESKTOP_OPTIONS="-d ITCTEST -u '' -p '' -P -z -f -r disk:E=/mnt/usbdevice -r sound:local"
SESSION_0_AUTOSTART=On

Still doesn´t Autostart, i just see the rdesktop window and keyboard is en_US.
If i use these options in terminal i get a connection with redirect etc. everything is fine.
The command is:
rdesktop -d ITCTEST -u '' -p '' -P -z -f -r disk:E=/mnt/usbdevice -r sound:local 192.168.110.2
I´ve also tried to take the server ip into the options line, i don´t know how your script and the variables work but i guess it´s something like:
rdesktop "SESSION_0_RDESKTOP_OPTIONS" "SESSION_0_RDESKTOP_SERVER"
so i´ve tried to exclude SESSION_0_RDESKTOP_SERVER by # it and took the server ip into the options line.
Same result, Rdesktop starts but i see only the window.

Hope this will help u fixing the problem.

Greetings

Seg

**Comment by Doncuppjr** [comment] 2018-12-06 01:06
Perhaps something else is now wrong. I did experience your reported issues, I found a problem and fixed it. I can confirm that the bochs and cirrus cards are now KMS.
    On Wednesday, December 5, 2018, 12:19:54 AM PST, Seg22 <notifications@github.com> wrote:  
 
 
Hey Thin,

first of all, my last Ticket "Install 6.1 on VM - not able to go graphical" isn´t done yet. I´ve tried to install the new 1201 iso in xen and now i only got a blackscreen, not even a command line.

Second:
I´ve updated Devstation via Start/DevStation/Update Devstation and build a new image.

Splash: still doesn´t work (i know you´ve excluded this, i hope just for now)

Keyboard: if i start xfwm4 first the keyboard is de_DE (in terminal and also in rdesktop if i start it then)
If i autostart directly into rdesktop the keyboard is en_US or sth. maybe this issue get´s together with the rdesktop issue

rdesktop: I´ve checkt my options through terminal and found out that -x l doesn´t work for us
so i´m now using:

SESSION_0_TITLE="ITCRemote"
SESSION_0_TYPE=rdesktop
SESSION_0_RDESKTOP_SERVER=192.168.110.2
SESSION_0_RDESKTOP_OPTIONS="-d ITCTEST -u '' -p '' -P -z -f -r disk:E=/mnt/usbdevice -r sound:local"
SESSION_0_AUTOSTART=On

Still doesn´t Autostart, i just see the rdesktop window and keyboard is en_US.
If i use these options in terminal i get a connection with redirect etc. everything is fine.
The command is:
rdesktop -d ITCTEST -u '' -p '' -P -z -f -r disk:E=/mnt/usbdevice -r sound:local 192.168.110.2
I´ve also tried to take the server ip into the options line, i don´t know how your script and the variables work but i guess it´s something like:
rdesktop "SESSION_0_RDESKTOP_OPTIONS" "SESSION_0_RDESKTOP_SERVER"
so i´ve tried to exclude SESSION_0_RDESKTOP_SERVER by # it and took the server ip into the options line.
Same result, Rdesktop starts but i see only the window.

Hope this will help u fixing the problem.

Greetings

Seg

**Comment by Seg22** [comment] 2018-12-10 09:52
Hey Don, sorry i don´t know what u wanna tell me^^

Anyway, i`ve now put the www-package into my image to get more debug options and found out that hes converting my options, which are: 

SESSION_0_RDESKTOP_OPTIONS="-d ITCTEST -u '' -p '' -P -z -f -r disk:USB/mnt/usbdevice -r sound:local"

into

SESSION_0_RDESKTOP_OPTIONS='-d ITCTEST -u '"' '"' -p '"' '"' -P -z -f -r disk:USB/mnt/usbdevice -r sound:local'

You can also see that in this image: [https://imgur.com/a/SWefa2r](url)
Maybe this will help you find the Problem.

And another thing with the www-Package, i cant shutdown the thinclient through the Administration.cgi (there was a poweroff.cgi before, wasn´t it?)
If i press on "halt" the syslog tells me: [https://imgur.com/a/4eNd4U7](url)

Would be grate if you´d have a look at it.

Thanks.

Seg

**Comment by Thinstation** [comment] 2018-12-13 18:41
I can't debug the rdesktop issue. It looks like it doesn't support newer protocols and can't connect to newer servers.

**Comment by Seg22** [comment] 2018-12-17 14:23
Hmm but the rdesktop in 5.5 could? I don´t think so, i´ve also deactivated CredSSP and tried different Servers.
Also, if i connect manually through the rdesktop window or through terminal it works fine.
Just the Autostart doesn´t work correctly.
I´ve tested very much different Settings now, also with freerdp but i can´t get an autostart into remote desktop.
Can you tell me where i find the logfile for autostart? Maybe i can find something there.
Or where is the script which uses the configs? Maybe i can put my options right into the script or smth.

Thanks

Seg

**Comment by Doncuppjr** [comment] 2018-12-17 16:04
set LOG_COMMANDS=truethen check/run/applications 
for logs.    On Monday, December 17, 2018, 6:23:38 AM PST, Seg22 <notifications@github.com> wrote:  
 
 
Hmm but the rdesktop in 5.5 could? I don´t think so, i´ve also deactivated CredSSP and tried different Servers.
Also, if i connect manually through the rdesktop window or through terminal it works fine.
Just the Autostart doesn´t work correctly.
I´ve tested very much different Settings now, also with freerdp but i can´t get an autostart into remote desktop.
Can you tell me where i find the logfile for autostart? Maybe i can find something there.
Or where is the script which uses the configs? Maybe i can put my options right into the script or smth.

Thanks

Seg

**Comment by Seg22** [comment] 2019-01-09 12:54
Hey there,

i´ve now fixed the Problem by editing the rdesktop.global and remove rdesktop.getip from /thinstation/build/packages/rdesktop/etc/cmd
I´ve just put all my options and the server ip into rdesktop.global, so i can´t change these ones anytime but thats ok for now.

Oh and for rdesktop and newer Servers you have to activate this:
[Picture](https://cloud.addictivetips.com/wp-content/uploads/2009/09/SystemProperties_thumb.jpg)
freerdp doesn´t need that.

I´ve than switched from my testlab to the running system in School, everything is set as in testlab, i´ve got the efi boot with bootx64.efi which then get the initrd and vmlinuz by http.

And here is the Problem, in my testlab everything works like a charm but in live system it says no such file or directory when it comes to load vmlinuz through http, so the tftp works.

I´ve already deactivated all firewalls/antivir and i can download the file from other computers with no problem, do you know what else can interrupt http while booting with efi?

Unfortunatelly it has to be efi but it don´t need to be http, what else can i use with the bootx64.efi? Do i only have to change the default config file in pxelinux.cfg folder?

Greetings

Seg

**Comment by Doncuppjr** [comment] 2019-01-09 13:00
I could only imagine what the problem is. What is the IP of the server hosting the files? Is it accessible from the client?


Sent from Yahoo Mail for iPhone


On Wednesday, January 9, 2019, 4:54 AM, Seg22 <notifications@github.com> wrote:


Hey there,

i´ve now fixed the Problem by editing the rdesktop.global and remove rdesktop.getip from /thinstation/build/packages/rdesktop/etc/cmd
I´ve just put all my options and the server ip into rdesktop.global, so i can´t change these ones anytime but thats ok for now.

Oh and for rdesktop and newer Servers you have to activate this:
Picture
freerdp doesn´t need that.

I´ve than switched from my testlab to the running system in School, everything is set as in testlab, i´ve got the efi boot with bootx64.efi which then get the initrd and vmlinuz by http.

And here is the Problem, in my testlab everything works like a charm but in live system it says no such file or directory when it comes to load vmlinuz through http, so the tftp works.

I´ve already deactivated all firewalls/antivir and i can download the file from other computers with no problem, do you know what else can interrupt http while booting with efi?

Unfortunatelly it has to be efi but it don´t need to be http, what else can i use with the bootx64.efi? Do i only have to change the default config file in pxelinux.cfg folder?

Greetings

Seg

**Comment by Seg22** [comment] 2019-01-09 13:19
IP is 172.16.0.120/22 and yes, i can ping from the efi shell, and if i access the file from windows i can download it like usual, just through efi boot it doesn´t work.

Actually i would like to use ftp or sth but it looks like that doesn´t work with ipxe/efi64, does it?

**Comment by Doncuppjr** [comment] 2019-01-09 15:28
When and where do you see file not found?
    On Wednesday, January 9, 2019, 5:19:35 AM PST, Seg22 <notifications@github.com> wrote:  
 
 
Yes, i can ping from the efi shell, and if i access the file from windows i can download it like usual, just through efi boot it doesn´t work.

Actually i would like to use ftp or sth but it looks like that doesn´t work with ipxe/efi64, does it?

**Comment by ghost** [comment] 2019-01-10 05:34
Has anyone fixed the splash screen error? This renders the latest thinstation ISO useless for my purposes. 

Splash screen error = ""a start job is running for start splash for 1:30 min"

**Comment by Seg22** [comment] 2019-01-10 09:35
I see it while booting after he get bootx64.efi, ldlinux.e64, product.txt and default via tftp, he shows the product.txt and in same screen i see:
http://172.16.0.120/Boot/vmlinuz no such file or directory

@novafiddler thats not an error, they deleted the possibility, we don´t know when it will work again.
Just change your build.conf and # the bootsplash

**Comment by Thinstation** [comment] 2019-01-10 16:41
What do you see in the server logs? Capital B looks suspicious.

**Comment by Doncuppjr** [comment] 2019-01-10 17:17
The error should be fixed, when was your last checkout? What kind of hardware?


Sent from Yahoo Mail for iPhone


On Wednesday, January 9, 2019, 9:34 PM, novafiddler <notifications@github.com> wrote:


Has anyone fixed the splash screen error? This renders the latest thinstation ISO useless for my purposes.

Splash screen error = ""a start job is running for start splash for 1:30 min"

**Comment by Seg22** [comment] 2019-01-11 14:20
Found the reason thanks to Wireshark:
[Picture](https://imgur.com/a/Hhj9ASA)

The error messages says he cant reach 172.16.0.90 but wireshark says he tries to get 172.16.0.100 (tftp server) even though i told him to get http://172.16.0.90/boot/vmlinuz in my default config, he sends the http request to the tftp server.

Now i got the tftp and the http on same server and he can boot finally.

Oh and rdesktop still got the wrong keyboard layout if started without a window manager, but you can tell the server to take his own layout instead getting the remote layout:

HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layout
New > DWORD
Name: IgnoreRemoteKeyboardLayout
value: 1

Thank you all for your help, now it finnaly can be closed.

Greetings

Seg

**Comment by Doncuppjr** [comment] 2019-01-11 14:58
Did you have a FASTBOOT_URL set?


Sent from Yahoo Mail for iPhone


On Wednesday, January 9, 2019, 4:54 AM, Seg22 <notifications@github.com> wrote:


Hey there,

i´ve now fixed the Problem by editing the rdesktop.global and remove rdesktop.getip from /thinstation/build/packages/rdesktop/etc/cmd
I´ve just put all my options and the server ip into rdesktop.global, so i can´t change these ones anytime but thats ok for now.

Oh and for rdesktop and newer Servers you have to activate this:
Picture
freerdp doesn´t need that.

I´ve than switched from my testlab to the running system in School, everything is set as in testlab, i´ve got the efi boot with bootx64.efi which then get the initrd and vmlinuz by http.

And here is the Problem, in my testlab everything works like a charm but in live system it says no such file or directory when it comes to load vmlinuz through http, so the tftp works.

I´ve already deactivated all firewalls/antivir and i can download the file from other computers with no problem, do you know what else can interrupt http while booting with efi?

Unfortunatelly it has to be efi but it don´t need to be http, what else can i use with the bootx64.efi? Do i only have to change the default config file in pxelinux.cfg folder?

Greetings

Seg

**Comment by Seg22** [comment] 2019-01-14 07:00
Nope, no fastboot URL is set just the net_file_alternate is set to the tftp.

**Comment by Thandror** [comment] 2019-01-16 18:14
I have also the Problem my keyboard layout is en_US when i autostart rdesktop. Any news on this?

**Comment by Thinstation** [comment] 2019-01-16 18:17
Likely an RDesktoP problem. The OS correctly sets the locale and keymap in the environment. If RDesktoP doesn't detect it correctly, there is nothing I can do.

**Closed by Thinstation** 2019-01-16 18:17 UTC
