### ISSUE TITLE
TS 6.1: hwclock not found

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#457] opened 2019-09-16 10:48 UTC
Hello!
I accidentally discovered that the cron task hwclock doesn't executing
```
journalctl | grep hwclock
Sep 16 13:01:00 ts_001d60054a63 crond[5936]: /bin/sh: hwclock: not found
Sep 16 13:01:00 ts_001d60054a63 crond[5936]: /bin/sh: hwclock: not found
Sep 16 14:01:00 ts_001d60054a63 crond[5936]: /bin/sh: hwclock: not found

```
You must set full path to hwclock.

**Comment by Doncuppjr** [comment] 2019-09-23 19:18
I'm not able to reproduce this error. All of my versions of busybox have the hwclock applet. Do you have a custom busybox?

**Comment by mcsn747** [comment] 2019-09-24 11:50
I'm cloned your repo a week ago, and hwclock is in sbin folder.
crontab -l
1 * * * * /etc/init.d/ntpd restart
1 * * * * hwclock -w
*/1 * * * * /bin/check_x11vnc
0  * * * * /bin/checklogs
All other entries include full path to executable. You must set full path to hwclock.

**Comment by Thinstation** [comment] 2019-09-26 15:21
Should be fixed in 6.2

**Closed as completed by Thinstation** 2019-09-26 15:21 UTC
