### ISSUE TITLE
X not starting with  VX855/VX875 Chrome 9 HCM Integrated Graphics

### ISSUE THREAD

**Issue by mb4262** [Thinstation/thinstation#124] opened 2016-02-26 12:30 UTC
I'm trying to build a thinstation image with TS-5.4.2 to PXE boot and open a freerdp session only. 

The devices I want to use have VX855/VX875 Chrome 9 HCM Integrated Graphics according to lspci. I've tired many variations of build.conf, my latest attempt is attached but X fails and the attached Xorg.0.log is very typical of the error I've been seeing. I'm building with --allmodules of course and following guidance I found around here I've enable all the X related packages except the nvida drivers which wanted a download when building and the download threw 404 errors. I've been scratching around for a couple of days and googled the life out this but really I'm beyond what I understand wrt to X and drivers for it.
Any assistance would be very welcome.  
Mike

[build_conf.txt](https://github.com/Thinstation/thinstation/files/148175/build_conf.txt)
[Xorg_0_log.txt](https://github.com/Thinstation/thinstation/files/148176/Xorg_0_log.txt)

**Comment by justinchevrier** [comment] 2016-02-29 20:44
This is most likely caused by a bug in the Via Openchrome driver. Recently development work has started up again after a long period of inactivity. Hopefully there will be a new release (0.3.4) soon. If you're able to test out the latest Openchrome GIT code give it a try, your crash may already be resolved in the development version. Check out Bugzilla as well and see if a similar bug has already been filed, or if a new one should be created:
https://bugs.freedesktop.org/buglist.cgi?product=xorg&component=Driver%2Fopenchrome&list_id=571067

Openchrome Git:
https://cgit.freedesktop.org/openchrome

**Comment by JBrumby** [comment] 2016-03-27 20:55
Thank you for the advice. I built the new package xorg7-openchrome.zip to overrwrite the original broken package. 


[xorg7-openchrome.zip](https://github.com/Thinstation/thinstation/files/191117/xorg7-openchrome.zip)

It is now working for me.
Julius

**Comment by trentasis** [comment] 2017-07-10 21:22
Solves!

**Comment by trentasis** [comment] 2017-07-11 18:00
I think that can be closed this issue...

**Closed** 2017-07-11 18:47 UTC
